site_name: DOCUMENTATION
site_url: https://sourav1570.github.io/Boss-AI-Toolkit-Documentation/
nav:
  - BOSS AI TOOLKIT:
    - Getting Started: GettingStarted.md
    - First Boss Setup: FirstBossSetup.md
    - Non Combat Behaviour: NonCombatBehaviour.md
    - Smart Turning Behaviour: SmartTurningBehaviour.md
    - Pre Combat Behaviour: PreCombatBehaviour.md
    - Melee Attack: MeleeAttack.md
    - Ground Slam: GroundSlam.md
    - Flame Thrower: FlameThrower.md
    - Charging Attack: Charging.md
    - Jump Attack: JumpAttack.md
    - Teleportation: Teleportation.md
    - Chase And Attack: ChaseAndAttack.md
    - Meteor Strike: MeteorStrike.md
    - Throw Weapon: Throw_Weapon.md
    - Projectile Attack: ProjectileAttack.md
    - Throw Objects: Throw_Objects.md
    - Spit Attack: Spit_Attack.md
    - Summon Minions: Summon_Minions.md
    - Boss Voices: Boss_Voices.md
    - Player Setup: Player_Setup.md
    - PC Controls: PC_Controls.md
    - Boss Health System: BossHealth.md
    - Player Vs Boss Setup: PlayerVsBoss_Setup.md
    - Player Vs Spider Boss Setup: PlayerVsSpiderBoss_Setup.md
    - Knight Enemy Setup: KnightEnemySetup.md
    - Spear Capturer Enemy Setup: SpearCapturerEnemySetup.md
    - Spear Spawner Enemy Setup: SpearSpawnerEnemySetup.md
    - Rock Thrower Enemy Setup: RockThrowerEnemySetup.md
    - Archer Enemy Setup: ArcherEnemySetup.md
docs_dir: docs
use_directory_urls: false
theme:
  name: material
  nav_style: default
  features:
    - navigation.tabs
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.copy.code
    - prev_next_buttons
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: white
      accent: white
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent:  black
plugins:
  - search
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/BeGy5hhyNj
    - icon: fontawesome/solid/envelope
      link: https://mail.google.com/
copyright: |
   &copy; 2026 <a href="Mobile Action Kit" target="_blank" rel="noopener">BossAIToolkit</a>